webhook_url: ...
message_id: ...
roblosecurity: ...
place_id: ...
vip_server_id: ...
server_region: ...
discord_id: ...
webhook_username: # Optional
webhook_url_shutdown: ...
avatar_url: # Optional
thumbnail_url: # Optional
